### ISSUE TITLE
spiff merge in below situation not working

### ISSUE THREAD

**Issue by gowrisankar22** [mandelsoft/spiff#10]
can someone help spiff merge issues for this case?

template.yaml

```
command: ["/cloud_sql_proxy",
                "-instances="(( .postgresconnectionnam ))"=tcp:5432"]
```
values.yaml 

```
postgresconnectionname: PROJECT:REGION:INSTANCE
```

spiff merge template.yml values.yml

 Output:

```
- /cloud_sql_proxy
- -instances=(( .postgresconnectionnam ))=tcp:5432
```

but the output should be
```
command:
- /cloud_sql_proxy
- -instances=PROJECT:REGION:INSTANCE=tcp:5432

```
I see that data is not getting interpolated. can someone help here?

**Comment by mandelsoft** [comment]
There are two errors in your example above:

- you refer to `.postgresconnectionnam` but define `postgresconnectionname` ( with trailing `e`).
- a dynaml expression cannot be used inside a string value, the complete value must be a dynaml expression

```yaml
command: 
  - "/cloud_sql_proxy",
  - (( "-instances="  .postgresconnectionname  "=tcp:5432" ))
```
