### ISSUE TITLE
Provide Windows binaries in Releases

### ISSUE THREAD

**Issue by ivanchuchulski** [mandelsoft/spiff#19]
Hello, 
My purpose is to have spiff locally for debugging some templates. 

I'd kindly ask if you could provide spiff binaries for Windows platform, if that's possible. What other alternative is there, if that's not possible? Maybe building from source - if so, how this could be done. Thanks in advance!

Kind Regards,
Ivan Chuchulski

**Comment by mandelsoft** [comment]
dev version now supports windows. Next release will include these variants.

**Comment by mandelsoft** [comment]
https://github.com/mandelsoft/spiff/releases/tag/v1.7.0-beta-6
