### ISSUE TITLE
Reference external files

### ISSUE THREAD

**Issue by jasonkuhrt** [mandelsoft/spiff#2]
This is a pretty cool project! I was wondering if any consideration has ever been made about support for external resources, either remote (across a network, e.g. something in a Github repo) or just somewhere else on disk. The remote case would be interesting if it was vcs aware allowing e.g. reference of a Git repo and tag to manage versioning.

**Comment by mandelsoft** [comment]
Basically the idea here is to have a local file sytem based basic tool. Therefore there is support for reading additional files. But nothing is planned for remote access.

If you have a good idea how this could look like, I'm open for adding something new.
I first step could be to extend the local file access to accpect URLs.

**Comment by jasonkuhrt** [comment]
My original use-case was helping deal with circleci configurations repeated across dozens of projects but circleci version 2.1 config has introduced modularity and "code reuse" features that effectively remove my original use-case.

**Comment by mandelsoft** [comment]
I've released a new version with some new features. It also includes http and https access.
Unfortunately I'm very busy with the gardener kubernetes project, so I have only limited time for my hobby (spiff :-). Once a year during the _year end holidays_ I find some time and an new release is borne.

Happy new year

**Comment by mandelsoft** [comment]
Now you even can add your own function and use a virtual filesystem, if you use the go library version of spiff.
