### ISSUE TITLE
add option to disable automatic line wrapping

### ISSUE THREAD

**Issue by Diaphteiros** [mandelsoft/spiff#9]
`spiff++` seems to automatically wrap long lines:

foo.yaml:
```yaml
wrapTest: a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
```

spiff merge foo.yaml =>
```yaml
wrapTest: a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
  a a a a a
```

It should somehow be possible to suppress this behaviour, as it e.g. screws with pattern matching.

**Comment by mandelsoft** [comment]
I've no influence on this, it is done by the marshalling.

Don't use pattern matching to extract information from yaml/json. A better way is to use tools like `jq` to access dedicated fields independent of the formatting.
